/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminSection;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import loginSection.LoginSection;

/**
 *
 * @author Patrick
 */
public class AdminSection extends javax.swing.JFrame {

    /**
     * Creates new form AdminSection
     */
    public AdminSection() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtEmployeeId = new javax.swing.JTextField();
        jComboBoxSeniorityLevel = new javax.swing.JComboBox<>();
        jTxtRole = new javax.swing.JTextField();
        jTxtPoints = new javax.swing.JTextField();
        jBtnAccruePoints = new javax.swing.JButton();
        jBtnSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBtnLogout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtMonths = new javax.swing.JTextField();
        jBtnClear = new javax.swing.JButton();
        jDateChooserDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Employee ID");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Start Date");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Seniority Level");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Role");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Points");

        jTxtEmployeeId.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTxtEmployeeId.setBorder(null);

        jComboBoxSeniorityLevel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jComboBoxSeniorityLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        jComboBoxSeniorityLevel.setBorder(null);

        jTxtRole.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTxtRole.setBorder(null);

        jTxtPoints.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTxtPoints.setBorder(null);

        jBtnAccruePoints.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnAccruePoints.setText("Accrue Points");
        jBtnAccruePoints.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jBtnAccruePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAccruePointsActionPerformed(evt);
            }
        });

        jBtnSubmit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnSubmit.setText("Submit");
        jBtnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Admin Section");

        jBtnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnLogout.setText("Logout");
        jBtnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("Tenure (Months)");

        jTxtMonths.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTxtMonths.setBorder(null);

        jBtnClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnClear.setText("Clear");
        jBtnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(306, 306, 306))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtEmployeeId, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jTxtMonths, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jComboBoxSeniorityLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(178, 178, 178))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnAccruePoints)
                        .addGap(62, 62, 62)
                        .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jBtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxSeniorityLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLogout)
                    .addComponent(jBtnSubmit)
                    .addComponent(jBtnAccruePoints)
                    .addComponent(jBtnClear))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAccruePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAccruePointsActionPerformed
        // TODO add your handling code here:
        String seniorityLevel;
        seniorityLevel = jComboBoxSeniorityLevel.getSelectedItem().toString();
        int months = Integer.parseInt(jTxtMonths.getText());  
        int id = Integer.parseInt(jTxtEmployeeId.getText());

        switch (seniorityLevel) {
            case "A":
                if (months <= 24) {

                    int points = (5 * 100) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");

                } else if (months <= 48) {
                    int points = (5 * 125) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else if (months >= 48) {
                    int points = (5 * 150) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid entry: Please Enter your correct tenure period");
                }
                break;
            case "B":
                if (months <= 24) {

                    int points = (10 * 100) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");

                } else if (months <= 48) {
                    int points = (10 * 125) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else if (months >= 48) {
                    int points = (10 * 150) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid entry: Please Enter your correct tenure period");
                }
                break;
            case "C":
                if (months <= 24) {

                    int points = (15 * 100) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");

                } else if (months <= 48) {
                    int points = (15 * 125) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else if (months >= 48) {
                    int points = (15 * 150) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid entry: Please Enter your correct tenure period");
                }
                break;
            case "D":
                if (months <= 24) {

                    int points = (20 * 100) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");

                } else if (months <= 48) {
                    int points = (20 * 125) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else if (months >= 48) {
                    int points = (20 * 150) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid entry: Please Enter your correct tenure period");
                }
                break;
            case "E":
                if (months <= 24) {

                    int points = (25 * 100) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");

                } else if (months <= 48) {
                    int points = (25 * 125) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");
                } else if (months >= 48) {
                    int points = (25 * 150) / 100;
                    jTxtPoints.setText(Integer.toString(points));
                    JOptionPane.showMessageDialog(null, "Employee of ID: " + id + " has accrued: " + points + " points given the Seniority level and tenure period");

                } else {

                    JOptionPane.showMessageDialog(this, "Invalid entry: Please Enter your correct tenure period");
                }
                break;

            default:
                JOptionPane.showMessageDialog(this, "Invalid Entry: Please Enter a correct character to represent your Seniority Level: A,B,C,D, or E");
                break;
        }


    }//GEN-LAST:event_jBtnAccruePointsActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        // TODO add your handling code here:

        jTxtEmployeeId.setText(null);
        jTxtMonths.setText(null);
        jTxtRole.setText(null);
        jTxtPoints.setText(null);

    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        // TODO add your handling code here:
        new loginSection.LoginSection().setVisible(true);
        dispose();


    }//GEN-LAST:event_jBtnLogoutActionPerformed

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/fenixemployee_db", "root", "root123");

            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String sql = "insert into fenixemployee(employee_id,start_date,months,seniority_level,role,points)" + "values('" + Integer.parseInt(jTxtEmployeeId.getText()) + "','" + sdf.format(jDateChooserDate.getDate()) + "','" + Integer.parseInt(jTxtMonths.getText()) + "','" + jComboBoxSeniorityLevel.getSelectedItem().toString() + "','" + jTxtRole.getText() + "','" + Integer.parseInt(jTxtPoints.getText()) + "')";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insertion Successful");
            conn.close();

            jTxtEmployeeId.setText(null);
            jTxtMonths.setText(null);
            jTxtRole.setText(null);
            jTxtPoints.setText(null);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_jBtnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAccruePoints;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JComboBox<String> jComboBoxSeniorityLevel;
    private com.toedter.calendar.JDateChooser jDateChooserDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtEmployeeId;
    private javax.swing.JTextField jTxtMonths;
    private javax.swing.JTextField jTxtPoints;
    private javax.swing.JTextField jTxtRole;
    // End of variables declaration//GEN-END:variables
}
